SALIR="salir"
ALTA="alta"
BAJA="baja"
CONSULTA="consultar"
MODIFICAR="modificar"

LISTAR_AUTORES="listar autores"
LISTAR_LIBROS="listar libros"
LISTAR_LIBROS_GENERO="listar libros de genero"
LISTAR_LIBROS_AUTOR="listar libros de autor"
LISTAR_LIBROS_EDITORIAL="listar libros de editorial"
LISTAR_LIBROS_EDITORIAL_EDICION="listar libros de editorial en rango de años"
LISTAR_EDITORIAL_AUTOR="listar autores de editorial"
LISTAR_LIBROS_AÑO="listar libros de un año"
LISTAR_LIBROS_AUTOR_LETRA="listar libros de un autor cuyo apellido empieza con letra"
LISTAR_LIBROS_PALABRA="listar libros que empiecen con palabra"
LISTAR="listar"

OPERACION_INVALIDA="Operacion invalida."
NO_HAY_LIBRO="No hay ningun libro con el titulo ingresado."
BASE_DE_DATOS_VACIA="Base de datos vacia."
AVISO="A continuacion ingrese el rango de años."
AVISO_SALIR="Ingrese salir para finalizar."
YA_ESTA="El libro ya se encuentra en la base de datos."
ESTA="El libro se encuentra en la base de datos."
NO_ESTA="El libro no se encuentra en la base de datos."

TITULO="titulo"
AUTOR="autor"
PAGINAS="paginas"
ISBN="isbn"
AÑO_EDICION="año"
EDITORIAL="editorial"
GENERO="genero"
NO="no"
SI="si"

OPERACION="Ingrese una operacion: "
DATOS="Ingrese datos para la operacion señalada (Separe los datos con ','): "
DATOS_MODIFICAR="Qué desea modificar? (Separe con ',' lo que desea modificar): "
TITULO_VIEJO="Ingrese el titulo del libro que desea modificar: "
TITULO_NUEVO="Ingrese el titulo nuevo: "
TITULO_PEDIDO="Ingrese el titulo del libro que desea modificar: "
AUTOR_PEDIDO="Ingrese el autor nuevo: "
PAGINAS_NUEVAS="Ingrese la cantidad de paginas nuevas: "
ISBN_NUEVO="Ingrese el ISBN nuevo: "
AÑO_NUEVO="Ingrese el año de edicion nuevo: "
EDITORIAL_NUEVA="Ingrese la editorial nueva: "
GENERO_NUEVO="Ingrese el genero nuevo: "

GENERO_LISTADO="Ingrese un genero: "
AUTOR_LISTADO="Ingrese un autor: "
EDITORIAL_LISTADO="Ingrese una editroial: "
RANGO_AÑOS_1_LISTADO="Ingrese el primer numero del rango: "
RANGO_AÑOS_2_LISTADO="Ingrese el segundo numero del rango: "
AÑO_LISTADO="Ingrse el año de edicion: "
PALABRA_LISTADO="Ingrese una palabra: "
LETRA_LISTADO="Ingrese una letra: "
